# Generated by Django 4.1.3 on 2022-11-25 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_skill_seekerskill_seekereducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('secondname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('relocation', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'applicants',
                'db_table': 'applicant',
                'ordering': ('created_at', '-updated_at'),
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('certification_awarded', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(choices=[('primary', 'Primary'), ('highschool', 'High School'), ('undergraduate', 'Undergraduate'), ('tertiary', 'Tertiary'), ('other', 'Other')], default='primary', max_length=50, verbose_name='education level')),
                ('institution_name', models.CharField(blank=True, max_length=60, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_education', to='job.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant_education',
                'verbose_name_plural': 'applicants_education',
                'db_table': 'applicanteducation',
                'ordering': ('created_at', '-updated_at'),
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_experience', to='job.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant_experience',
                'verbose_name_plural': 'applicants_experience',
                'db_table': 'applicantexperience',
                'ordering': ('created_at', '-updated_at'),
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('skill_level', models.CharField(blank=True, max_length=20, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_skill', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_skill', to='job.skill')),
            ],
            options={
                'verbose_name': 'applicant_skill',
                'verbose_name_plural': 'applicants_skill',
                'db_table': 'applicantskill',
                'ordering': ('created_at', '-updated_at'),
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='seekereducation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='seekereducation',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='seekerexperience',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='seekerexperience',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='seekerskill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='seekerskill',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='seekerskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Seeker',
        ),
        migrations.DeleteModel(
            name='SeekerEducation',
        ),
        migrations.DeleteModel(
            name='SeekerExperience',
        ),
        migrations.DeleteModel(
            name='SeekerSkill',
        ),
    ]
