# Generated by Django 4.1.3 on 2022-11-25 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_companyaddress'),
        ('job', '0003_applicant_applicanteducation_applicantexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_data', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_post', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jobpost',
                'verbose_name_plural': 'jobspost',
                'db_table': 'jobpost',
                'ordering': ('created_at', '-updated_at'),
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='applicantskill',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='beginner', max_length=30, verbose_name='skill level'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under_Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=30, verbose_name='application status')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantapplication', to='job.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpostapplication', to='job.jobpost')),
            ],
            options={
                'verbose_name': 'jobapplication',
                'verbose_name_plural': 'jobapplications',
                'db_table': 'jobapplication',
                'ordering': ('created_at', '-updated_at'),
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JobPostSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='beginner', max_length=30, verbose_name='skill level')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpostskillset', to='job.jobpost')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillset', to='job.skill')),
            ],
            options={
                'verbose_name': 'jobpostskill',
                'verbose_name_plural': 'jobspostskills',
                'db_table': 'jobpostskill',
                'ordering': ('created_at', '-updated_at'),
                'unique_together': {('jobpost', 'skill')},
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
