# Generated by Django 4.1.3 on 2022-11-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobpost_alter_applicantskill_skill_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
